version: 2
updates:
  - package-ecosystem: "pip"       # Use pip for Python deps
    directory: "/"                 # Root of the repo
    schedule:
      interval: "weekly"           # Check once per week


