version: 2
updates:
  - package-ecosystem: "pip"       # We are using pip (Python dependencies in requirements.txt)
    directory: "/"                 # Root directory of the repo
    schedule:
      interval: "weekly"           # Run once a week
      day: "monday"                # Every Monday
      time: "07:00"                # At 07:00 in the morning
      timezone: "Europe/Berlin"    # Use Berlin timezone
    open-pull-requests-limit: 2    # Maximum of 2 open PRs at the same time
    allow:
      - dependency-type: "direct"  # Only update direct dependencies, not transitive ones
    groups:
      prod-minor-and-patch:        # Group all minor and patch updates into one PR
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - dependencies               # Add "dependencies" label to PRs
      - security                   # Add "security" label to PRs
    ignore:
      - dependency-name: "*"       # Ignore all major version updates (breaking changes)
        update-types:
          - "version-update:semver-major"

