name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      # smoke test: importă aplicația (nu pornește serverul)
      - run: python - <<'PY'
          import run
          print("import ok")
        PY
